version: '3'

networks:
  backend-test-transfeera:
    name: backend-test-transfeera

services:
  mongodb:
    image: mongo
    hostname: mongo
    container_name: mongodb
    ports: [ 27017:27017 ]
    networks: [ backend-test-transfeera ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/db --quiet 1
      timeout: 20s
      retries: 10
